/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DeliveryPartners } from "./DeliveryPartners";
import { DeliveryPartnersCountArgs } from "./DeliveryPartnersCountArgs";
import { DeliveryPartnersFindManyArgs } from "./DeliveryPartnersFindManyArgs";
import { DeliveryPartnersFindUniqueArgs } from "./DeliveryPartnersFindUniqueArgs";
import { DeleteDeliveryPartnersArgs } from "./DeleteDeliveryPartnersArgs";
import { DeliveryPartnersService } from "../deliveryPartners.service";
@graphql.Resolver(() => DeliveryPartners)
export class DeliveryPartnersResolverBase {
  constructor(protected readonly service: DeliveryPartnersService) {}

  async _deliveryPartnersItemsMeta(
    @graphql.Args() args: DeliveryPartnersCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [DeliveryPartners])
  async deliveryPartnersItems(
    @graphql.Args() args: DeliveryPartnersFindManyArgs
  ): Promise<DeliveryPartners[]> {
    return this.service.deliveryPartnersItems(args);
  }

  @graphql.Query(() => DeliveryPartners, { nullable: true })
  async deliveryPartners(
    @graphql.Args() args: DeliveryPartnersFindUniqueArgs
  ): Promise<DeliveryPartners | null> {
    const result = await this.service.deliveryPartners(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DeliveryPartners)
  async deleteDeliveryPartners(
    @graphql.Args() args: DeleteDeliveryPartnersArgs
  ): Promise<DeliveryPartners | null> {
    try {
      return await this.service.deleteDeliveryPartners(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
